services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: votia
      POSTGRES_PASSWORD: votia
      POSTGRES_DB: votia
    ports:
      - "5434:5432"
    volumes:
      - votia_pg:/var/lib/postgresql/data

volumes:
  votia_pg:
